# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-07 13:14
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kalkuta', '0002_auto_20170106_1817'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cilji',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(max_length=30)),
                ('trenutno_stanje', models.FloatField()),
                ('ciljno_stanje', models.FloatField()),
                ('rok', models.DateField(default=datetime.datetime.now)),
                ('datum', models.DateField(default=datetime.datetime.now)),
                ('uporabnik', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Stanje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stanje', models.FloatField()),
                ('uporabnik', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
