# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-07 13:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kalkuta', '0004_auto_20170107_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stanje',
            name='stanje',
            field=models.FloatField(default=0),
        ),
    ]
