# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-07 13:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kalkuta', '0005_auto_20170107_1442'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cilji',
            name='trenutno_stanje',
        ),
        migrations.AlterField(
            model_name='cilji',
            name='ciljno_stanje',
            field=models.FloatField(default=-2),
        ),
    ]
