# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-07 14:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kalkuta', '0006_auto_20170107_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stanje',
            name='uporabnik',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
