# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-08 10:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kalkuta', '0007_auto_20170107_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='transakcija',
            name='leto_trans',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='transakcija',
            name='mesec_trans',
            field=models.IntegerField(choices=[(1, 'Januar'), (2, 'Februar'), (3, 'Februar'), (4, 'Februar'), (5, 'Februar'), (6, 'Februar'), (7, 'Februar'), (8, 'Februar'), (9, 'Februar'), (10, 'Februar'), (11, 'Februar'), (12, 'Februar')], null=True),
        ),
    ]
