# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-08 20:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kalkuta', '0008_auto_20170108_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transakcija',
            name='mesec_trans',
            field=models.IntegerField(null=True),
        ),
    ]
