# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-08 20:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kalkuta', '0009_auto_20170108_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='cilji',
            name='leto_trans',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='cilji',
            name='mesec_trans',
            field=models.IntegerField(null=True),
        ),
    ]
