# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-09 19:19
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kalkuta', '0011_auto_20170109_2019'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cilji',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(max_length=30)),
                ('ciljno_stanje', models.FloatField(default=-2)),
                ('rok', models.DateField(default=datetime.datetime.now)),
                ('uspesnost', models.IntegerField(default=-1)),
                ('leto_trans', models.IntegerField(null=True)),
                ('mesec_trans', models.IntegerField(null=True)),
                ('uporabnik', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Stanje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stanje', models.FloatField(default=0)),
                ('uporabnik', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transakcija',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tip', models.BooleanField()),
                ('visina', models.FloatField()),
                ('datum', models.DateTimeField(default=datetime.datetime.now)),
                ('leto_trans', models.IntegerField(null=True)),
                ('mesec_trans', models.IntegerField(null=True)),
                ('uporabnik', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
